version: "3.9"

services:
  discord-bot:
    image: registry.ultraxime.fr/discord-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    stdin_open: true
    tty: true
    # configs:
    #   - config
    volumes:
      - type: bind
        source: discord-bot.yml
        target: /config
    networks:
      - administration

# configs:
#   config:
#     file: discord-bot.yml
networks:
  administration:
    name: administration
    external: true
