version: "3.9"

services:
  discord-bot:
    image: discord-bot
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      restart_policy: 
        condition: on-failure
    stdin_open: true
    tty: true
    # configs:
    #   - config
    volumes:
      - type: bind
        source: discord-bot.yml
        target: /config

# configs:
#   config:
#     file: discord-bot.yml
